verity-team/dws

- dws/package.json
- dws/src/components/ClientRoot.tsx
- dws/src/components/common/TextButton.tsx
- dws/src/components/common/TextError.tsx
- dws/src/components/metamask/DemoConnectButton.tsx
- dws/src/components/metamask/DonateForm.tsx
- dws/src/components/metamask/donate/Donate.tsx
- dws/src/components/metamask/donate/DonateForm.tsx
- dws/src/components/metamask/donate/TokenSelector.tsx
- dws/src/utils/types.ts
- dws/yarn.lock
> Feature: Prototype donate UI

- dws/src/components/metamask/donate/DonateForm.tsx
- dws/src/components/stats/user/UserStat.tsx
> Feature: Disable donation based on donation/data status

- deployments/db/01-schema.sql
- internal/buck/db/db.go
- internal/buck/ethereum/txs.go
- internal/buck/ethereum/txs_test.go
> add block hash to donation record

- deployments/db/01-schema.sql
- internal/buck/db/db.go
- internal/buck/ethereum/txs.go
- internal/buck/ethereum/txs_test.go
> add block time to donation record

- deployments/db/01-schema.sql
- internal/buck/db/db.go
- internal/buck/ethereum/txs.go
> add blocks we failed to parse to the `failed_blocks` table

- cmd/buck/main.go
- deployments/db/01-schema.sql
- internal/buck/db/db.go
- internal/buck/ethereum/txs.go
- internal/buck/ethereum/txs_test.go
- internal/common/buck.go
> add transactions we failed to parse to the `failed_tx` table

- internal/delphi/db/db.go
- internal/delphi/server/server.go
> fix broken sql

- dws/src/app/api/donation/data/route.ts
- dws/src/components/metamask/donatev2/form/DonateForm.tsx
resolve #50 
- Change endpoint from `/donation/data/` to `/donation/data`
> Fix: Remove trailing slash for `donation/data` endpoint

- dws/src/app/api/donation/affiliate/route.ts
- dws/src/components/metamask/donatev2/form/DonateForm.tsx
- dws/src/utils/api/clientAPI.ts
- dws/src/utils/api/types.ts
- dws/src/utils/api/types/affliate.type.ts
- dws/src/utils/api/types/campaign.type.ts
- dws/src/utils/api/types/index.ts
- dws/src/utils/api/types/userData.type.ts
- dws/src/utils/utils.ts
- Request to server to associate affiliate code from URL with current wallet address (after user have connected their wallet to our site)
resolve #51 
resolve #49 
Testing will be done later when the backend server is up and running
> Fix: Request to server to associate wallet address with affiliate code

- deployments/db/01-schema.sql
> allocate more db space for finalized block tx hashes

- cmd/tt/main.go
- internal/delphi/server/server.go
> return "400 Bad request" + error in case of stale timestamp

- api/delphi.yaml
- cmd/tt/main.go
- internal/delphi/server/server.go
> derive message to sign from REST endpoint path

- dws/src/components/ClientRoot.tsx
- dws/src/components/landing/banner/Banner.tsx
- dws/src/components/landing/carousel/MemeSlideshow.tsx
- dws/src/components/landing/footer/LandingFooter.tsx
- dws/src/components/landing/navbar/ConnectBtn.tsx
- dws/src/components/landing/navbar/Navbar.tsx
- dws/src/components/landing/roadmap/Roadmap.tsx
- dws/src/components/metamask/donatev2/AFCForm.tsx
- dws/src/components/metamask/donatev2/Donate.tsx
- dws/src/utils/metamask/wallet.ts
- dws/yarn.lock
> Fix: Update signature message format

- internal/pulitzer/data/binance.go
> fix binance price

- dws/src/app/api/affiliate/connect/route.ts
- dws/src/app/api/affiliate/gen/route.ts
- dws/src/components/ClientRoot.tsx
- dws/src/components/metamask/donatev2/Donate.tsx
- dws/src/utils/api/clientAPI.ts
- dws/src/utils/api/types/affiliate.type.ts
- Add function call to request connecting affiliate code (if any) with user wallet address
- Fix typo from `affliate` to `affiliate`
> Fix: Missing function call when connect wallet

- cmd/buck/main.go
- internal/buck/db/db.go
> add feature to process a single block, latest or final

- dws/src/components/ClientRoot.tsx
- dws/src/components/metamask/donatev2/AFCForm.tsx
- dws/src/components/metamask/donatev2/form/ConnectBtn.tsx
- dws/src/components/metamask/wallet/ConnectModal.tsx
- dws/src/components/stats/user/UserStat.tsx
- Fix some visual bugs when opening and closing "Switch account" modal
> Fix: Improve switch UX

- cmd/buck/main.go
- internal/buck/ethereum/txs.go
> ignore malformed erc20 txs

- cmd/buck/main.go
>  buck/final: only process finalized blocks as needed

- cmd/buck/main.go
- cmd/pulitzer/main.go
- deployments/db/01-schema.sql
- internal/buck/db/db.go
- internal/buck/ethereum/block_number.go
- internal/buck/ethereum/block_number_test.go
- internal/buck/ethereum/common.go
- internal/buck/ethereum/txs.go
- internal/common/buck.go
> process all finalized blocks and refactor it to use the same code as latest

- cmd/buck/main.go
- env.example
- internal/buck/ethereum/block.go
- internal/buck/ethereum/block_number.go
- internal/buck/ethereum/block_test.go
- internal/buck/ethereum/common.go
- internal/buck/ethereum/txs.go
- internal/buck/ethereum/txs_test.go
- internal/common/buck.go
> cache finalized blocks on disk

- Makefile
- internal/buck/db/db.go
- internal/buck/ethereum/block.go
- internal/buck/ethereum/common.go
> fetch a fresh copy of cached block file in case of json parsing failure

- internal/buck/db/db.go
- internal/common/buck.go
- internal/common/buck_test.go
> switch campaign status to 'closed' once a maximum of tokens has been sold 

- Makefile
- api/delphi.yaml
- api/server.go
- cmd/buck/main.go
- cmd/delphi/main.go
- cmd/pulitzer/main.go
- env.example
- internal/delphi/server/server.go
> make the age of the auth timestamp configurable with a 30 second default

- api/delphi.yaml
- api/server.go
- internal/delphi/server/server.go
> return status 200 (and empty user data) as opposed to status 404

- internal/delphi/db/db.go
- internal/delphi/server/server.go
> POST /wallet/connection -- ignore requests with affiliate codes that do NOT exist in the database

- internal/delphi/db/db.go
- internal/delphi/server/server.go
> simplify the wallet connect logic

- dws/package.json
- dws/src/app/page.tsx
- dws/src/components/landing/carousel/UploadMemeBtn.tsx
- dws/src/utils/api/baseAPI.ts
- dws/src/utils/api/client/memeAPI.ts
- Upload meme with optional caption
> Feature: User can upload meme

- dws/src/app/api/meme/route.ts
- dws/src/components/landing/carousel/UploadMemeBtn.tsx
- dws/src/utils/api/baseAPI.ts
- dws/src/utils/api/client/memeAPI.ts
- Add a route handler for handling meme upload
- Add support for form data for base APIs, server APIs and client APIs
> Feature: Meme upload route handler

- dws/package-lock.json
- dws/package.json
- dws/src/api/galactica/meme/meme.tsx
- dws/src/api/galactica/meme/meme.type.ts
- dws/src/app/fonts.ts
- dws/src/app/meme/layout.tsx
- dws/src/app/meme/page.tsx
- dws/src/components/galactica/account/SignInBtn.tsx
- dws/src/components/galactica/meme/MemeInput.tsx
- dws/src/components/galactica/meme/MemeList.tsx
- dws/src/components/galactica/meme/MemePage.tsx
- dws/src/components/galactica/meme/list/MemeList.tsx
- dws/src/components/galactica/meme/list/MemeListItem.tsx
- dws/src/hooks/galactica/meme/useMeme.tsx
- dws/src/utils.d.ts
- dws/src/utils/baseAPI.ts
- dws/src/utils/utils.ts
- dws/tsconfig.json
- Add infinite scrolling list of memes
- Optimistically displaying meme after user upload
- Fix SIWE not accepting user wallet address
- Fix SIWE using the wrong account to sign the sign-in message
> Feature: Displaying memes from server and from user upload

- dws/src/app/admin/page.tsx
- dws/src/components/admin/list/AdminMemeListItem.tsx
- Use `DWS_AT_KEY` for both user and admin access token
> Fix: Admin endpoint does not use admin access token

- dws/.env.example
- dws/src/app/layout.tsx
- dws/src/app/meme/layout.tsx
- dws/src/app/meme/page.tsx
- dws/src/components/galactica/account/SignInBtn.tsx
- dws/src/components/galactica/meme/MemeTimeline.tsx
- dws/src/components/galactica/meme/common/MemeNavbar.tsx
- dws/src/components/galactica/meme/input/MemeInput.tsx
- dws/src/components/galactica/meme/list/MemeListItem.tsx
- dws/src/hooks/galactica/account/useNonce.tsx
- Migrate `/meme` UI to new theme and for mobile view
- Add failsafe for requesting nonce
- Update flow so user can skip signature signing when they have signed earlier
> Fix: Fix unexpected behavior in meme page authentication

- dws/package-lock.json
- dws/package.json
- dws/src/api/dws/user/user.ts
- dws/src/components/ClientRoot.tsx
- dws/src/components/galactica/account/SignInBtn.tsx
- dws/src/components/galactica/meme/MemeTimeline.tsx
- dws/src/components/galactica/meme/common/MemeNavbar.tsx
- dws/src/components/galactica/meme/input/MemeInput.tsx
- dws/src/components/ico/donatev2/AFCForm.tsx
- dws/src/components/ico/donatev2/form/ConnectBtn.tsx
- dws/src/components/ico/donatev2/form/DonateForm.tsx
- dws/src/components/ico/donatev2/form/ThankDialog.tsx
- dws/src/components/ico/stats/user/DonationStat.tsx
- dws/src/components/ico/stats/user/UserDonationStat.tsx
- dws/src/hooks/galactica/account/useAccessToken.tsx
- Resolve #152 
- Resolve #150 
- Resolve #141
- Resolve #137
- Issues #151
> Fix: Resolve major issues

- dws/src/api/dws/email/email.ts
- dws/src/components/landing/newsletter/Newsletter.tsx
- dws/src/utils/baseApiV2.ts
> Fix: Update email subscription handling

- dws/src/components/ClientRoot.tsx
- dws/src/components/walletconnect/ConnectModalv2.tsx
- dws/src/components/walletconnect/config.ts
- Handle more cases when trying to connect from saved wallet and provider from `localStorage`
> Fix: Fix persist wallet connection not working as expected

- dws/public/community.html
- dws/public/js/webflow.js
- dws/public/memes.html
- dws/public/nft.html
- dws/public/story.html
- dws/public/token.html
> Fix: Patch webflow.js to allow email subscription on static webpages

- dws/src/api/galactica/admin/admin.ts
- dws/src/app/admin/page.tsx
- Add message toast when admin input a wrong username + password combination
> Fix: Update admin sign in flow

- internal/pulitzer/data/kraken.go
> make sure array is not empty before accessing it
